// templates/vue-python/frontend/src/App.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <header class="bg-white shadow">
      <div class="mx-auto max-w-7xl px-4 py-6">
        <h1 class="text-3xl font-bold text-gray-900">Welcome</h1>
      </div>
    </header>
    <main class="mx-auto max-w-7xl px-4 py-6">
      <p class="text-gray-500">Your app is running.</p>
    </main>
  </div>
</template>

// templates/react-flask/frontend/src/App.tsx
export default function App() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow">
        <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900">
            Welcome
          </h1>
        </div>
      </header>
      <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <p className="text-gray-500">Your app is running.</p>
      </main>
    </div>
  );
}
